### ISSUE TITLE
Estimar requisitos com o cliente

### ISSUE THREAD

**Issue by Arthur-Henrique-Andrade-Farias** [Arthur-Henrique-Andrade-Farias/virtual-badge#1]

**Comment by Arthur-Henrique-Andrade-Farias** [comment]
Enviar um e-mail para o Awdren, coordenador do LEDES, para verificar o que exatamente ele espera que façamos com relação ao aplicativo, obtendo assim os devidos requisitos.

**Comment by lohanTT** [comment]
Fiz o envio do e-mail contendo a seguinte mensagem:

"
Boa tarde, professor. Tudo bem?

Precisava falar contigo, em nome do meu grupo, sobre o desafio a ser entregue: Hoje nos reunimos pelo horário de almoço para termos um primeiro contato e tomarmos as primeiras decisões.

Nesse sentido, acerca do escopo do projeto: Em primeiro momento percebemos que não tínhamos muita clareza em relação aos objetivos do projeto, qual problema ele tenta solucionar ou qual processo ele tenta tornar mais efetivo, e também outras questões que nos ajudariam a elencar os requisitos. Duas sugestões foram dadas: Tomar a liberdade para fazer essas definições, baseadas num cenário inventado ou fazer a descoberta a partir de um "stakeholder" fora do projeto. Ponderamos muito em relação aos riscos relacionados ao tempo de entrega.

Em suma, gostaríamos de compreender melhor o escopo do projeto: Objetivo do projeto, os interessados no projeto, os tipos de usuários do projeto.

Outra questão, trivial, porém importante: Todos os e-mails relacionados ao projeto devem manter a formatação de assunto e os membros em cópia ou apenas o último, de entrega?
"

**Comment by lohanTT** [comment]
Novo e-mail:

"
Validações que surgiram:

- Usuários comuns podem buscar e alterar os dados referentes a si, este deve passar por validação do usuário adm. Usuários comuns não podem criar ou deletar dados.
- Usuários administradores podem buscar dados não sensíveis referentes a usuários comuns. Podem criar, alterar e deletar dados. 

Questões que surgiram:

- Considerando o crachá enquanto ferramenta de autenticação, o acesso de usuários mediante identificação e senha é considerado suficiente ou o crachá deve apresentar códigos de barras/qr para validação via sistema?
- Nesse sentido, o escopo do projeto engloba a leitura e permissão de acesso via crachá? Ou é de responsabilidade deste módulo apenas funcionalidades CRUD dos crachás?
"

**Comment by lohanTT** [comment]
**RESPOSTA**

Vou responder em linha.

Em ter., 23 de jan. de 2024 às 16:38, LOHAN TOLEDO TOSTA <[lohan.toledo@ufms.br](mailto:lohan.toledo@ufms.br)> escreveu:
Validações que surgiram:

- Usuários comuns podem buscar e alterar os dados referentes a si, este deve passar por validação do usuário adm. Usuários comuns não podem criar ou deletar dados.
R: Certo. 
- Usuários administradores podem buscar dados não sensíveis referentes a usuários comuns. Podem criar, alterar e deletar dados. 
R: Não. 

Questões que surgiram:

- Considerando o crachá enquanto ferramenta de autenticação, o acesso de usuários mediante identificação e senha é considerado suficiente ou o crachá deve apresentar códigos de barras/qr para validação via sistema?
R: Se quiserem apresentar algo a mais, sintam-se a vontade. Porém, o básico é o acesso mediante identificação e senha.
 
- Nesse sentido, o escopo do projeto engloba a leitura e permissão de acesso via crachá? Ou é de responsabilidade deste módulo apenas funcionalidades CRUD dos crachás?
R: Pode ser uma funcionalidade a mais. Mas o módulo principal o CRUD.
