### ISSUE TITLE
Colher todos os requisitos com o cliente, antes de iniciar um backlog mais estruturado para a aplicação.

### ISSUE THREAD

**Issue by Arthur-Henrique-Andrade-Farias** [Arthur-Henrique-Andrade-Farias/virtual-badge#2]

**Comment by lohanTT** [comment]
Documento elaborado. Ainda existem pendências:
- Validação com stakeholder
- Inclusão dos dados faltantes, representados pelas chaves [INSERIR]

Ainda para ser adicionado ao repositório. Porém disponível para leitura no link:
https://docs.google.com/document/d/1M8kyvwKXMQ5Oh4sO1s6wCRfDaJpArTdK/edit?usp=sharing&ouid=114023371587039754277&rtpof=true&sd=true

Issue em progresso...

**Comment by lohanTT** [comment]
**EMAIL DE VALIDAÇÃO**

"Boa noite, Awdren.

Foi esboçado pelo time um documento de requisitos, com requisitos funcionais apenas. Gostaríamos, se possível, de ter uma validação dele. 

Ele se encontra no link, junto de outros documentos que elaboramos: https://docs.google.com/document/d/1M8kyvwKXMQ5Oh4sO1s6wCRfDaJpArTdK/edit?usp=sharing&ouid=114023371587039754277&rtpof=true&sd=true"

Aguardando resposta.

**Comment by lohanTT** [comment]
Documento adicionado ao repositório, no commit [fb6db02]

**Comment by lohanTT** [comment]
**RESPOSTA DE VALIDAÇÃO DE REQUISITOS**

"Olá, bom dia! Acabei de ler, gostei."

Ainda resta a definição dos campos faltantes no documento.

**Comment by lohanTT** [comment]
Documento de requisitos disponível no diretorio /docs

Desde o commit 3f525f5
